services:
  ps05-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: ps05-gpu-challenge
    gpus: all
    ports:
      - "8000:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONPATH=/app
      - TRANSFORMERS_CACHE=/app/models
      - HF_HOME=/app/models
      - MPLCONFIGDIR=/tmp
      - YOLO_CONFIG_DIR=/tmp
      - HF_HUB_OFFLINE=0
      - TRANSFORMERS_OFFLINE=0
      # Optional specialized models
      - LAYOUTLMV3_CHECKPOINT=/app/models/layoutlmv3-6class
      - CHART_CAPTION_CHECKPOINT=/app/models/pix2struct-chart
      - TABLE_T2T_CHECKPOINT=/app/models/table-t2t
      # Optional OCR engine selection
      - USE_PADDLEOCR=1
      - CUDA_LAUNCH_BLOCKING=0
      - TORCH_CUDNN_V8_API_ENABLED=1
      - TORCH_CUDNN_V8_API_DISABLED=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_LAYOUTLM=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_YOLO=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_BLIP=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_OCR=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_FASTTEXT=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_TRANSFORMERS=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_ULTRALYTICS=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_EASYOCR=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_PIL=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_OPENCV=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_NUMPY=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_PANDAS=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_SCIPY=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_MATPLOTLIB=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_SEABORN=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_PLOTLY=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_SCIKIT_LEARN=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_NLTK=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_SPACY=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_ALBUMENTATIONS=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_IMGAUG=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_IMAGEHASH=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_PYMUPDF=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_PYPDF2=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_PYTHON_DOCX=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_PYTHON_PPTX=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_FASTAPI=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_UVICORN=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_PYTHON_MULTIPART=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_PYDANTIC=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_AIOHTTP=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_ASYNCIO_MQTT=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_PATHLIB2=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_WATCHDOG=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_LOGURU=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_PROMETHEUS_CLIENT=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_PYTEST=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_PYTEST_ASYNCIO=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_BLACK=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_FLAKE8=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_MYPY=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_CUPY_CUDA12X=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_NUMBA=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_ONNX=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_ONNXRUNTIME_GPU=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_TENSORRT=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_ACCELERATE=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_DEEPSPEED=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_TENSORBOARD=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_WANDB=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_TQDM=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_CLICK=0
      - TORCH_CUDNN_V8_API_DISABLED_FOR_RICH=0
    volumes:
      - ./datasets:/app/datasets
      - ./results:/app/results
      - ./models:/app/models
      - ./logs:/app/logs
      - ./backend:/app/backend
      - ./scripts:/app/scripts
      - "D:/IIT/docai/data/train:/app/data/api_datasets"
      - ./data/api_results:/app/data/api_results
      # Example: mount a specific evaluation dataset (read-only)
      # - /data/ps05_eval/<DATASET_ID>/images:/app/data/api_datasets/<DATASET_ID>/images:ro
      # Example: persist API-managed datasets/results on host (optional)
      # - /data/ps05_api_datasets:/app/data/api_datasets
      # - /data/ps05_results:/app/data/api_results
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: ps05-gpu-network
